"""empty message

Revision ID: 839b79e1c615
Revises: 
Create Date: 2018-08-09 19:35:56.925219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '839b79e1c615'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('neighborhood', sa.Column('area', sa.String(length=255), nullable=True))
    op.add_column('neighborhood', sa.Column('year', sa.String(length=255), nullable=True))
    op.drop_column('neighborhood', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('neighborhood', sa.Column('type', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.drop_column('neighborhood', 'year')
    op.drop_column('neighborhood', 'area')
    # ### end Alembic commands ###
